-- ============================================================================
-- Loom — TEST DATA (generated). NOT part of the schema, NOT real knowledge.
--
-- 15 cards so the feed, Threads and the lineage strip can be looked at with
-- something in them. Every id starts with test-, every origin is 'test', and
-- every title ends in [TEST] — three independent ways to tell these from the
-- six real canvas cards, which start with cv-.
--
-- People: only the real roster (documented_by must reference persons), so no
-- new invented names enter the database. The cards themselves are invented,
-- which is what [TEST] says out loud.
--
-- Remove with db/testdata_delete.sql — one statement, nothing else touched.
-- ============================================================================
begin;

insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-01', 'project', 'test', 'doubleu', 'du-minwoo', null, null, null, array['AI Video Pipeline','Slack Integration']::text[], null, null, '{"en":{"title":"Batch renders overnight without a babysitter [TEST]","summary":"Queue drains by morning; failures retry themselves.","made":"An overnight queue for the video pipeline: everything submitted after 18:00 renders while nobody is watching.","solved":"A submit -> poll -> verify unit per job, with a retry that checks whether the previous attempt finished before spending credits again.","borrow":"The verify-before-retry check. Without it a flaky provider costs double for every hiccup."},"ko":{"title":"밤새 렌더를 사람 없이 돌리기 [TEST]","summary":"아침이면 큐가 비어 있고, 실패는 스스로 재시도됩니다.","made":"비디오 파이프라인용 야간 큐 — 18시 이후 제출분은 아무도 지켜보지 않는 사이 렌더됩니다.","solved":"작업당 submit → poll → verify 단위, 재시도 전에 이전 시도가 끝났는지 확인해 크레딧 낭비를 막습니다.","borrow":"재시도 전 검증. 이게 없으면 제공자가 흔들릴 때마다 비용이 두 배가 됩니다."}}'::jsonb, 'en', null, now() - interval '96 days', '{"value":3,"unit":"month"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-02', 'experiment', 'test', 'whow', 'wh-bengt', null, null, null, array['QA Gate','AI Video Pipeline']::text[], null, null, '{"en":{"title":"How many QA checks is too many [TEST]","summary":"Eight checks caught more; twelve caught nothing new and cost a minute.","goal":"Find where the vision QA gate stops paying for itself.","method":"Ran the same 200 generations through gates of four, eight and twelve checks.","happened":"Eight caught 94% of what twelve caught. Twelve added 55 seconds per request.","learned":"The last four checks were re-asking the first four in different words."},"ko":{"title":"QA 검사는 몇 개가 과한가 [TEST]","summary":"8개는 더 잡았고, 12개는 새로 잡는 것 없이 1분을 더 썼습니다.","goal":"비전 QA 게이트가 값을 못 하기 시작하는 지점 찾기.","method":"같은 생성물 200건을 4개·8개·12개 검사 게이트로 통과시켰습니다.","happened":"8개가 12개가 잡은 것의 94%를 잡았습니다. 12개는 요청당 55초를 더 썼습니다.","learned":"마지막 4개는 처음 4개를 다른 말로 다시 묻고 있었습니다."}}'::jsonb, 'en', null, now() - interval '88 days', '{"value":3,"unit":"month"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-03', 'project', 'test', 'whow', 'wh-felix', 'test-02', 'builtOn', 'The QA numbers decided how many checks this one ships with.', array['Format Adaptation','Motion Adaptation','Character Animation']::text[], null, null, '{"en":{"title":"One comp, five formats, no hand-rebuilding [TEST]","summary":"The slot stays; everything around it adapts.","made":"A format adaptation rig: build at 1:1, get 16:9, 5:4, 9:16 and 4:5 out of the same comp.","solved":"The animated sub-comp is never touched. Layout, scale, spacing, logo and effects are driven per format by expressions.","borrow":"Keeping the motion untouched is the whole trick — everything else is layout arithmetic."}}'::jsonb, 'en', null, now() - interval '74 days', '{"value":2,"unit":"month"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-04', 'update', 'test', 'doubleu', 'du-sua', null, null, null, array['Character Animation','Render Time']::text[], null, null, '{"en":{"title":"Character rig exports 3x faster after one pass [TEST]","summary":"Nothing clever — the cache was off.","note":"Turned the disk cache back on for the character rig exports and they went from nine minutes to three. It had been off since a debugging session in June."}}'::jsonb, 'en', null, now() - interval '61 days', '{"value":2,"unit":"month"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-05', 'question', 'test', 'whow', 'wh-mira', null, null, null, array['Localisation','Format Adaptation']::text[], 'open', 'doubleu', '{"en":{"title":"Do localised captions need their own safe area? [TEST]","summary":"German runs 30% longer and our lower third does not know it.","blocked":"Captions built for English overflow the lower third in German and Turkish, and we keep fixing it per asset.","triedSoFar":"Tried a fixed 15% margin, which looks wrong in English and still clips Turkish.","openQuestion":"How does DoubleU handle text length across languages in motion work?","conversation":["Captions built for English overflow the lower third in German and Turkish. Anyone solved this properly?"]}}'::jsonb, 'en', '[{"author":"Mira Keller","studio":"whow","timeValue":55,"timeUnit":"day"}]'::jsonb, now() - interval '55 days', '{"value":8,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-06', 'project', 'test', 'doubleu', 'du-minwoo', 'test-01', 'continuedFrom', 'The overnight queue made the spending invisible, so the gate came next.', array['Credit Gate','AI Video Pipeline','Slack Integration']::text[], null, null, '{"en":{"title":"A credit gate that warns before it stops you [TEST]","summary":"Soft warning at 70%, hard stop before the spend.","made":"Spend tracking inside the pipeline: a soft warning in the thread at 70% of the monthly budget, a hard stop before any request that would cross it.","solved":"The workflow tracks its own spend per request and a provider-side limit is the backstop, because our own counter can be wrong.","borrow":"Two limits, not one: yours to be polite, theirs to be certain."},"ko":{"title":"막기 전에 알려주는 크레딧 게이트 [TEST]","summary":"70%에서 부드러운 경고, 지출 직전에 완전 정지.","made":"파이프라인 내부 지출 추적 — 월 예산 70%에서 스레드에 경고, 초과하는 요청 직전에 정지.","solved":"워크플로가 요청별 지출을 자체 집계하고, 제공자 측 한도가 최종 방어선입니다. 우리 카운터는 틀릴 수 있으니까요.","borrow":"한도는 둘: 예의를 위한 우리 것, 확실함을 위한 그들 것."}}'::jsonb, 'en', null, now() - interval '47 days', '{"value":7,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-07', 'experiment', 'test', 'doubleu', 'du-minji', null, null, null, array['Onboarding','Retention']::text[], null, null, '{"en":{"title":"Shorter onboarding, measured properly this time [TEST]","summary":"Three screens beat five, but only with the permission ask moved.","goal":"Find out whether the onboarding length or the permission prompt was doing the damage.","method":"Four cohorts: five screens, three screens, and each with the permission ask early or late.","happened":"Three screens with a late ask completed 18pp more often. Three screens with an early ask was the worst of the four.","learned":"It was never the length. It was being asked for something before anything had been given."}}'::jsonb, 'en', null, now() - interval '40 days', '{"value":6,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-08', 'update', 'test', 'whow', 'wh-bengt', null, null, null, array['Slack Integration','QA Gate']::text[], null, null, '{"en":{"title":"Progress pings now say which step, not just that it is alive [TEST]","summary":"One line changed; the questions stopped.","note":"Progress messages now name the stage instead of posting a heartbeat. Support stopped asking whether it had hung, which was most of the questions.","next":"Same treatment for the browser track, where the steps are slower and the silence is longer."}}'::jsonb, 'en', null, now() - interval '33 days', '{"value":5,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-09', 'project', 'test', 'whow', 'wh-felix', 'test-03', 'appliedFrom', 'Same rig, retuned for social crops where the logo has nowhere to go.', array['Motion Adaptation','Format Adaptation']::text[], null, null, '{"en":{"title":"The rig, retuned for social crops [TEST]","summary":"Vertical needed different rules, not different code.","made":"The format rig extended to 9:16 social crops for the jackpot assets.","solved":"Vertical has no room beside the slot, so the logo moves above and the effects lose one layer. Same expressions, different numbers.","borrow":"The numbers are the port. The structure carried over untouched."},"ko":{"title":"소셜 크롭용으로 재조정한 리그 [TEST]","summary":"세로는 다른 코드가 아니라 다른 규칙이 필요했습니다.","made":"잭팟 에셋용 9:16 소셜 크롭까지 포맷 리그를 확장.","solved":"세로에서는 슬롯 옆 공간이 없어 로고가 위로 가고 효과 레이어 하나를 뺍니다. 같은 익스프레션, 다른 숫자.","borrow":"이식되는 건 숫자입니다. 구조는 그대로 넘어왔습니다."}}'::jsonb, 'en', null, now() - interval '28 days', '{"value":4,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-10', 'question', 'test', 'doubleu', 'du-minwoo', null, null, null, array['Render Time','Credit Gate']::text[], 'discussion', 'whow', '{"en":{"title":"Cap the slow renders, or let them finish? [TEST]","summary":"Eight minutes is fine until someone is waiting.","blocked":"A browser-track render can take eight minutes, and we cannot tell a slow one from a hung one.","triedSoFar":"Progress pings help, but they do not answer whether to kill it.","openQuestion":"Does Whow cap per-request render time, and at what?","conversation":["Do you cap render time per request, or let a slow one run? Ours can sit at eight minutes.","We cap it, but the cap is generous. A hung job costs more in questions than in credits."]}}'::jsonb, 'en', '[{"author":"Minwoo Heo","studio":"doubleu","timeValue":21,"timeUnit":"day"},{"author":"Bengt Ott","studio":"whow","timeValue":18,"timeUnit":"day"}]'::jsonb, now() - interval '21 days', '{"value":3,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-11', 'experiment', 'test', 'whow', 'wh-mira', null, null, null, array['Localisation','Onboarding']::text[], null, null, '{"en":{"title":"Do localised event names still beat translations? [TEST]","summary":"Yes, and by more than last year.","goal":"Re-run last year’s localisation test now that the catalogue is bigger.","method":"Region-written names against direct translations, six regions, three weeks.","happened":"Click-through improved in every region; Turkey and Poland by the most.","learned":"The gap grew where the catalogue grew. More choices makes the name matter more."},"de":{"title":"Schlagen lokalisierte Event-Namen Übersetzungen noch? [TEST]","summary":"Ja, und stärker als letztes Jahr.","goal":"Den Lokalisierungstest vom Vorjahr mit größerem Katalog wiederholen.","method":"Regional geschriebene Namen gegen direkte Übersetzungen, sechs Regionen, drei Wochen.","happened":"Die Klickrate stieg in jeder Region, am stärksten in der Türkei und Polen.","learned":"Der Abstand wuchs dort, wo der Katalog wuchs."}}'::jsonb, 'en', null, now() - interval '16 days', '{"value":2,"unit":"week"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-12', 'update', 'test', 'doubleu', 'du-sua', null, null, null, array['Character Animation']::text[], null, null, '{"en":{"title":"Rig presets are in the shared library now [TEST]","summary":"Copy-paste between projects is over.","note":"The character rig presets moved into the shared library, so a new project starts from the same six controls instead of somebody’s last file."}}'::jsonb, 'en', null, now() - interval '11 days', '{"value":11,"unit":"day"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-13', 'project', 'test', 'doubleu', 'du-minwoo', 'test-06', 'solvedThrough', 'The gate answered the spending question the architecture note left open.', array['Architecture Doc','Pipeline Architecture','Slack Integration']::text[], null, null, '{"en":{"title":"Architecture note, second pass [TEST]","summary":"What changed after a quarter of running it.","made":"An updated architecture note for the pipeline: what the first version got wrong and what the queue and the credit gate changed.","solved":"Three sequential stages became two plus a queue. The QA gate moved before delivery instead of after generation.","borrow":"The ordering, mostly. Checking before you deliver is cheaper than apologising after."},"ko":{"title":"아키텍처 노트, 두 번째 판 [TEST]","summary":"한 분기 돌려본 뒤 무엇이 달라졌는가.","made":"파이프라인 아키텍처 노트 갱신 — 첫 판이 틀렸던 것, 큐와 크레딧 게이트가 바꾼 것.","solved":"순차 3단계가 2단계+큐가 됐습니다. QA 게이트는 생성 직후가 아니라 전달 직전으로 옮겼습니다.","borrow":"주로 순서입니다. 전달 전에 검사하는 게 사과보다 쌉니다."},"de":{"title":"Architektur-Notiz, zweiter Durchgang [TEST]","summary":"Was sich nach einem Quartal Betrieb geändert hat.","made":"Aktualisierte Architektur-Notiz: was die erste Version falsch hatte und was Queue und Credit-Gate verändert haben.","solved":"Aus drei sequenziellen Stufen wurden zwei plus Queue. Das QA-Gate sitzt jetzt vor der Auslieferung.","borrow":"Vor allem die Reihenfolge."},"tr":{"title":"Mimari notu, ikinci geçiş [TEST]","summary":"Bir çeyrek çalıştırdıktan sonra ne değişti.","made":"Boru hattı için güncellenmiş mimari notu: ilk sürümün yanlışları ve kuyruk ile kredi kapısının değiştirdikleri.","solved":"Üç sıralı aşama, iki aşama artı kuyruğa dönüştü. QA kapısı teslimden önceye taşındı.","borrow":"Çoğunlukla sıralama."}}'::jsonb, 'en', null, now() - interval '6 days', '{"value":6,"unit":"day"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-14', 'update', 'test', 'whow', 'wh-bengt', null, null, null, array['Pipeline Architecture','Credit Gate']::text[], null, null, '{"en":{"title":"Provider swap done; two models still to tune [TEST]","summary":"Same shape, new engine.","note":"The generator runs on the new provider. Stills are good, video needs another pass on motion strength.","openQuestion":"Anyone found a motion-strength setting that survives a character close-up?"}}'::jsonb, 'en', null, now() - interval '3 days', '{"value":3,"unit":"day"}'::jsonb);
insert into knowledge_items (id, type, origin, origin_studio_id, documented_by_id, derived_from_id, relation_type, relation_note, keywords, status, asked_to_studio_id, body, source_lang, conversation, created_at, demo_age) values ('test-15', 'question', 'test', 'whow', 'wh-felix', null, null, null, array['Motion Adaptation','Render Time']::text[], 'open', 'doubleu', '{"en":{"title":"Half-resolution motion tests — useful or misleading? [TEST]","summary":"Faster to review, but easing looks different small.","blocked":"Reviewing motion at full resolution is slow; at half it is fast but the easing reads differently.","triedSoFar":"Tried half resolution at full frame rate, which is better than half of both.","openQuestion":"Does DoubleU review motion at reduced resolution, and does it catch what full does?","conversation":["Is anyone rendering motion tests at half resolution to review faster, or does that hide the problems?"]}}'::jsonb, 'en', '[{"author":"Felix Heitmann","studio":"whow","timeValue":1,"timeUnit":"day"}]'::jsonb, now() - interval '1 days', '{"value":1,"unit":"day"}'::jsonb);

insert into applications (knowledge_item_id, studio_id, project_id) values ('test-01', 'whow', 'whow-jackpot-social-generator');
insert into applications (knowledge_item_id, studio_id, project_id) values ('test-03', 'doubleu', 'doubleu-ai-video-pipeline');
insert into applications (knowledge_item_id, studio_id, project_id) values ('test-06', 'whow', null);
insert into applications (knowledge_item_id, studio_id, project_id) values ('test-07', 'whow', null);
insert into applications (knowledge_item_id, studio_id, project_id) values ('test-13', 'whow', null);

commit;

-- check: select count(*) from knowledge_items where origin = 'test';  -- 15